apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress

resources:
  - https://app.getambassador.io/yaml/emissary/3.8.2/emissary-crds.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/linkerd.io~1inject
        value: enabled
    target:
      kind: Namespace
      name: emissary-system
  - patch: |-
      - op: replace
        path: /metadata/name
        value: ingress
    target:
      kind: Namespace
      name: emissary-system
