namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/native?ref=v0.13.11
  - metallb-config.yaml

patches:
  - target:
      kind: Namespace
      name: metallb-system
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          istio-injection: disabled
