ipam:
  mode: kubernetes
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
socketLB:
  hostNamespaceOnly: true
l2announcements:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true

kubeProxyReplacement: true
k8sServiceHost: loom-dev-control-plane
k8sServicePort: 6443
