---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-istio
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/istio
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-istio
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/observability/dev
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-istio
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/weave-gitops
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-istio
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kubernetes-dashboard
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metallb
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-istio
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metal-lb
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-istio
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cert-manager
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ingress
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-kubernetes-dashboard
      namespace: flux-system
    - name: infra-weave-gitops
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/ingress
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
