# Hassle: the base Linkerd setup needs to have the linkerd-trust-anchor in place,
# so the secret can be passed to the Helm chart. We can only sequence these events by
# using separate Kustomizations and adding a dependency between them with Flux.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd

resources:
  - linkerd-crds.yaml
  - linkerd-trust-anchor.yaml
  - namespace.yaml
  - repository.yaml
