---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-selfsigned-issuer
  namespace: linkerd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-trust-anchor
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  issuerRef:
    name: linkerd-selfsigned-issuer
  subject:
    organizations:
      - Loom
    organizationalUnits:
      - linkerd
