apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - grafana.yaml
  - loki.yaml
  - promtail.yaml
  - repository.yaml
  - tempo.yaml
