---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: grafana
spec:
  interval: 30m
  targetNamespace: grafana
  releaseName: grafana-tempo
  chart:
    spec:
      chart: tempo-distributed
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h
  values:
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftHttp:
          enabled: true
      opencensus:
        enabled: false
    minio:
      enabled: false
    storage:
      trace:
        backend: s3
        s3:
          bucket: "tempo-traces"
          endpoint: "minio.minio:9000"
          insecure: true
  valuesFrom:
    - kind: Secret
      name: minio-root
      valuesKey: root-user
      targetPath: storage.trace.s3.access_key
    - kind: Secret
      name: minio-root
      valuesKey: root-password
      targetPath: storage.trace.s3.secret_key
