---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-jaeger
  annotations:
    linkerd.io/inject: enabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    linkerd.io/extension: jaeger
