---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: ingress
spec:
  interval: 30m
  targetNamespace: ingress
  releaseName: emissary-ingress
  chart:
    spec:
      chart: emissary-ingress
      version: "8.x"
      sourceRef:
        kind: HelmRepository
        name: emissary
        namespace: ingress
      interval: 12h
  values:
    waitForApiext:
      deploymentNamespace: ingress
    agent:
      enabled: false
    module: false
    service:
      nameOverride: emissary-ingress
      labels:
        announce: l2
      annotations:
        "io.cilium/lb-ipam-ips": "172.18.255.50"
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: emissary-ingress
            patch:
              - op: add
                path: /metadata/labels/loom-lang.announce
                value: l2
