---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: kubernetes-dashboard
  namespace: istio-system
spec:
  parentRefs:
    - name: dev-gateway
      namespace: istio-system
  hostnames:
    - "k8s.loom-lang.dev"
  rules:
    - backendRefs:
        - name: kubernetes-dashboard
          namespace: kubernetes-dashboard
          port: 443
