apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loom-lang-dev
  namespace: ingress
spec:
  secretName: loom-lang-dev-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
    - "*.loom-lang.dev"
  privateKey:
    rotationPolicy: Always
