---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 5m
  targetNamespace: linkerd
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      version: "1.x-edge"
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 1m
