apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v0.8.0
  - cloudflare-api-key.yaml
  - cert-issuers.yaml
  - istio-certs.yaml
