---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-signoz
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: loom-infra
  path: ./infrastructure/monitoring/signoz
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-linkerd-viz
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: monitoring-signoz
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: loom-infra
  path: ./infrastructure/monitoring/linkerd-viz
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-linkerd-jaeger
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: monitoring-signoz
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: loom-infra
  path: ./infrastructure/monitoring/linkerd-jaeger
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-weave-gitops
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: loom-infra
  path: ./infrastructure/monitoring/weave-gitops
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-kubernetes-dashboard
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: loom-infra
  path: ./infrastructure/monitoring/kubernetes-dashboard
  prune: true
  wait: true
