---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-smi
  namespace: linkerd-smi
spec:
  interval: 30m
  targetNamespace: linkerd-smi
  releaseName: linkerd-smi
  chart:
    spec:
      version: "1.x"
      chart: linkerd-smi
      sourceRef:
        kind: HelmRepository
        name: linkerd-smi
      interval: 12h
