---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: grafana
spec:
  interval: 30m
  dependsOn:
    - name: grafana-loki
      namespace: grafana
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h
  values:
    clients:
      - url: http://loki-gateway.grafana.svc.cluster.local/loki/api/v1/push
