apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - self-signed-issuer.yaml
