---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 30m
  targetNamespace: linkerd-viz
  releaseName: linkerd-viz
  chart:
    spec:
      version: "30.x"
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 12h
  values:
    grafana:
      externalUrl: https://grafana.loom-lang.dev/
    prometheus:
      enabled: true
    jaegerUrl: jaeger.linkerd-jaeger:16686
