---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
  labels:
    linkerd.io/is-control-plane: "true"
    linkerd.io/control-plane-ns: linkerd
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-smi
  annotations:
    linkerd.io/inject: enabled
  labels:
    linkerd.io/extension: smi
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  annotations:
    linkerd.io/inject: enabled
  labels:
    linkerd.io/extension: viz
