---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: linkerd-jaeger
spec:
  interval: 30m
  targetNamespace: linkerd-jaeger
  releaseName: linkerd-jaeger
  chart:
    spec:
      version: "30.x-edge"
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 12h
  values:
    collector:
      config:
    jaeger:
      enabled: false
  # Hassle: we have to use a post renderer here to set the config because for some reason the default Helm template
  # setup in linkerd-jaeger strips out the receiver and extension sections.
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: ConfigMap
              name: collector-config
            patch:
              - op: replace
                path: /data/collector-config
                value: |
                  receivers:
                    opencensus:
                  processors:
                    batch:
                    resource:
                      attributes:
                        - key: k8s.pod.name
                          from_attribute: host.name
                          action: insert
                        - key: k8s.namespace.name
                          from_attribute: linkerd.io/workload-ns
                          action: insert
                    k8sattributes:
                      auth_type: serviceAccount
                      pod_association:
                        - sources:
                            - from: resource_attribute
                              name: k8s.pod.name
                            - from: resource_attribute
                              name: k8s.namespace.name
                      extract:
                        metadata:
                          - k8s.pod.name
                          - k8s.pod.uid
                          - k8s.deployment.name
                          - k8s.node.name
                          - k8s.namespace.name
                          - k8s.pod.start_time
                          - k8s.replicaset.name
                          - k8s.replicaset.uid
                          - k8s.daemonset.name
                          - k8s.daemonset.uid
                          - k8s.job.name
                          - k8s.job.uid
                          - k8s.cronjob.name
                          - k8s.statefulset.name
                          - k8s.statefulset.uid
                          - container.image.name
                          - container.image.tag
                          - container.id
                          - k8s.container.name
                          - container.image.name
                          - container.image.tag
                          - container.id

                        labels:
                          - tag_name: kube_app_name
                            key: app.kubernetes.io/name
                            from: pod
                          - tag_name: kube_app_instance
                            key: app.kubernetes.io/instance
                            from: pod
                          - tag_name: kube_app_version
                            key: app.kubernetes.io/version
                            from: pod
                          - tag_name: kube_app_component
                            key: app.kubernetes.io/component
                            from: pod
                          - tag_name: kube_app_part_of
                            key: app.kubernetes.io/part-of
                            from: pod
                          - tag_name: kube_app_managed_by
                            key: app.kubernetes.io/managed-by
                            from: pod
                  extensions:
                    health_check:
                  exporters:
                    jaeger:
                      endpoint: signoz-otel-collector.signoz:14250
                      tls:
                        insecure: true
                  service:
                    extensions: [health_check]
                    pipelines:
                      traces:
                        receivers: [opencensus]
                        processors: [resource, k8sattributes, batch]
                        exporters: [jaeger]
